### ISSUE TITLE
Duplicate seeds across threads in RandomState with std feature?

### ISSUE THREAD

**Issue by Imberflur** [orlp/foldhash#12]
<https://github.com/orlp/foldhash/blob/4f19fe6c349603824b381d375cd9f591c8371f98/src/seed.rs#L35-L42>

This looks like it will produce the same sequence of seeds on each thread. Am I missing something?

This doesn't seem ideal, at least the non-std version below appears to try to avoid duplicate seeds across threads.

**Comment by orlp** [comment]
Hmm, I think you're right, I should change that.
